services:
  django:
    build: .
    container_name: django_portfolio_app
    expose:
      - "8000"
    volumes:
      - portfolio_app_static_data:/app/staticfiles
      - portfolio_app_media_data:/app/media
    depends_on:
      - db
    networks:
      - django_db
  db:
    image: postgres:17-alpine
    container_name: postgres_portfolio_app
    env_file:
      - .env
    networks:
      - django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  django_db:
    driver: bridge

  proxy_network:
    external: true

volumes:
  postgres_data:

  portfolio_app_static_data:
    external: true

  portfolio_app_media_data:
    external: true