# Generated by Django 5.1.4 on 2025-03-07 22:58

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_skill_topic_remove_project_technologies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("show", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
        migrations.RemoveField(
            model_name="about",
            name="skills",
        ),
        migrations.AddField(
            model_name="about",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="about/"),
        ),
        migrations.AddField(
            model_name="skill",
            name="show",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to=app.models.project.project_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.skillarea"
            ),
        ),
    ]
