# Generated by Django 5.1.4 on 2025-03-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_skillarea_alter_about_options_remove_about_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
            ],
            options={
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.DeleteModel(
            name="About",
        ),
        migrations.AddField(
            model_name="skillarea",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
