# Generated by Django 5.1.4 on 2025-03-08 00:03

import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_profile_delete_about_skillarea_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="TagulousTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name="project",
            name="tagulous_topics",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                autocomplete_view="admin:project_topic_autocomplete",
                blank=True,
                help_text="Enter a comma-separated tag string",
                to="app.taguloustopic",
            ),
        ),
    ]
