# Generated by Django 5.1.4 on 2025-03-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_topic_name_taguloustopic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tagulous_topics",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="formation",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="topics",
        ),
        migrations.RemoveField(
            model_name="project",
            name="topics",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TagulousTopic",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
