# Generated by Django 5.1.4 on 2025-03-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_topic_certification_topics_experience_topics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
