# Generated by Django 5.1.4 on 2025-03-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_project_company_project_end_date_project_start_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProjectImage",
        ),
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.CharField(default="Projeto Pessoal", max_length=100),
        ),
    ]
