# Generated by Django 5.1.4 on 2025-03-18 22:31

import app.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_certification_created_at_certification_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                storage=app.models.project.OverwriteStorage(),
                upload_to=app.models.project.project_directory_path,
            ),
        ),
    ]
