# Generated by Django 5.1.4 on 2026-05-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='description_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_pt_br',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pt_br',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skillarea',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skillarea',
            name='name_pt_br',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
