# Generated by Django 5.1.4 on 2026-05-27 20:50

from django.db import migrations
from django.db.models import F, Q


def _without_rewrite(queryset):
    rewrite = getattr(queryset, "rewrite", None)
    return rewrite(False) if callable(rewrite) else queryset


def backfill_pt_br(apps, schema_editor):
    models_fields = {
        "Experience": ("title", "description"),
        "Formation": ("title", "description"),
        "Profile": ("description",),
        "Project": ("title", "description"),
        "SkillArea": ("name",),
        "Skill": ("name",),
        "Certification": ("title", "description"),
    }

    for model_name, fields in models_fields.items():
        model = apps.get_model("app", model_name)
        queryset = _without_rewrite(model.objects)

        for field in fields:
            pt_field = f"{field}_pt_br"
            missing_pt = Q(**{f"{pt_field}__isnull": True}) | Q(**{pt_field: ""})
            queryset.filter(missing_pt).update(**{pt_field: F(field)})


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_certification_description_en_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_pt_br, migrations.RunPython.noop),
    ]
