# Generated by Django 5.1.4 on 2025-04-11 19:23

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_news_newstranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="company",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="description",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="title",
        ),
        migrations.CreateModel(
            name="ExperienceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="app.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "experience Translation",
                "db_table": "app_experience_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(
                parler.models.TranslatableModel,
                models.Model,
            ),  # TranslatedFieldsModelMixin
        ),
    ]
