# Generated by Django 5.1.4 on 2026-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_backfill_pt_br_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
